### ISSUE TITLE
XL Grid Should extend full width

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#1]
per gucci example

**Comment by JenSparks** [comment]
@GVFTW The comps show the left and right edges aligning with the left and right edges of the header container which has a max-width of 1560px. If the container for this instance of the collection template is different then we'll need a comp showing the differences to build toward.

Some other aspects of concern that come to mind are: 
- the filtering and sorting container widths
- how it relates to the page when the drawer is open

Breaking the main container like you're describing will cause a decent amount of template conditions on your layout.liquid template that will result in some messy changes. Doing it right so the code is clean would require significant changes across all templates to accommodate this.
