### ISSUE TITLE
Sort Menu

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#11]
**On Desktop**
Please add padding to top so its flush with filter bar

looks like
<img width="215" alt="screen shot 2017-03-23 at 4 41 55 pm" src="https://cloud.githubusercontent.com/assets/3649059/24269446/a625cf98-0fe7-11e7-8316-5031bbeddb4c.png">

should look like
<img width="248" alt="screen shot 2017-03-23 at 4 33 36 pm" src="https://cloud.githubusercontent.com/assets/3649059/24269190/b0a8c138-0fe6-11e7-8a57-61d80442f60f.png">

-------------------------------

**On Mobile**
Please use browser default menu

looks like
<img width="373" alt="screen shot 2017-03-23 at 4 17 13 pm" src="https://cloud.githubusercontent.com/assets/3649059/24268615/ba22bad6-0fe4-11e7-8abb-7dbb1dc16d79.png">

should like

ios
![img_5217](https://cloud.githubusercontent.com/assets/3649059/24268711/118c6fba-0fe5-11e7-875c-e3ef163ef9e4.PNG)

android os
![capture _2017-03-23-16-19-30](https://cloud.githubusercontent.com/assets/3649059/24268716/1bdb9e3c-0fe5-11e7-9633-b2b673a1fb24.png)

**Comment by JenSparks** [comment]
@GVFTW Desktop and Mobile have been updated.

For desktop, added top padding so it now looks like this:
https://www.dropbox.com/s/3htma3s0tpd3g0r/Screenshot%202017-03-29%2022.58.32.png?dl=0
