### ISSUE TITLE
Item Details / Product Meta

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#2]
**General**
should be - 
.item-details {
 opacity: .9;
}

<img width="310" alt="screen shot 2017-03-23 at 1 53 37 pm" src="https://cloud.githubusercontent.com/assets/3649059/24262350/21b071d0-0fd0-11e7-8d06-f0a391dab003.png">

-------------------------------------------------

**XL Viewport**
please lower item details to cover image below like Large viewport (it ended up covering too much of the image)

looks like 
<img width="296" alt="screen shot 2017-03-23 at 1 55 00 pm" src="https://cloud.githubusercontent.com/assets/3649059/24262460/6f975b48-0fd0-11e7-947d-1cf17108bf5b.png">

should look like
<img width="304" alt="screen shot 2017-03-23 at 1 54 43 pm" src="https://cloud.githubusercontent.com/assets/3649059/24262481/8382ae14-0fd0-11e7-8fda-712f701cbbae.png">

---------------------------------------------------

**On Mobile**

Text / Stars look off center

<img width="379" alt="screen shot 2017-03-23 at 2 44 47 pm" src="https://cloud.githubusercontent.com/assets/3649059/24264633/787d9bc6-0fd7-11e7-8247-00b84c9755de.png">

**Comment by GVFTW** [comment]
swatches should drop window beneath to cover item below

**Comment by GVFTW** [comment]
background opacity should be .9

**Comment by Aves3888** [comment]
- main image gets very lo-res & pixelated when you flip through swatches.
- should consistently show the same information (beanie doesn't show swatch but alpine styles do; if there is only a single cw, we need to either never show it or always show it)

**Comment by JenSparks** [comment]
@GVFTW Updated!
