### ISSUE TITLE
Cycling thru Swatches

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#4]
- Load time is slow

- Image res is blurry

<img width="626" alt="screen shot 2017-03-23 at 2 05 04 pm" src="https://cloud.githubusercontent.com/assets/3649059/24262868/d5033604-0fd1-11e7-9f2f-4d015c5e9411.png">

**Comment by JenSparks** [comment]
@GVFTW Updated.

Image resolution increased though this only increases the load-time of the images so we added a loading animation so shoppers know something is happening. Let us know if this is acceptable.
