### ISSUE TITLE
Sort Button

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#7]
**On Mobile**
Text z-indexing over main navigation
or you may need to put these in "is-moved-by-drawer" class
<img width="370" alt="screen shot 2017-03-23 at 2 36 23 pm" src="https://cloud.githubusercontent.com/assets/3649059/24264250/349aaf76-0fd6-11e7-913f-638e32dc298e.png">

**Comment by JenSparks** [comment]
@GVFTW Updated!
