### ISSUE TITLE
Collection Title 

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#8]
Vertically center collection title and description

looks like
<img width="376" alt="screen shot 2017-03-23 at 2 39 16 pm" src="https://cloud.githubusercontent.com/assets/3649059/24264494/fc39051e-0fd6-11e7-875e-f4efc0d4bcaa.png">

should look like
<img width="375" alt="screen shot 2017-03-23 at 2 43 22 pm" src="https://cloud.githubusercontent.com/assets/3649059/24264537/22f4c634-0fd7-11e7-913f-1a292a382a36.png">

**Comment by JenSparks** [comment]
@GVFTW  Updated top and bottom margins to match. Now should look like this:
https://www.dropbox.com/s/3wvrua5is7mfqla/Screenshot%202017-03-29%2023.33.49.png?dl=0
