### ISSUE TITLE
Back to Top Button

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#9]
Please un-anchor it (not sure if thats what they call it) once it hits the footer.

Around here would be great -

<img width="1198" alt="screen shot 2017-03-23 at 2 52 35 pm" src="https://cloud.githubusercontent.com/assets/3649059/24264971/65bccd3a-0fd8-11e7-9256-33ea2030cd4f.png">

**Comment by JenSparks** [comment]
@GVFTW Updated!
